#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.


import argparse  # pylint: disable=C0413
import json  # pylint: disable=C0413
import pprint  # pylint: disable=C0413
import sys  # pylint: disable=C0413

sys.path.append('../..')

import lib.base  # pylint: disable=C0413
import lib.disk  # pylint: disable=C0413
import lib.url  # pylint: disable=C0413


__author__ = 'Linuxfabrik GmbH, Zurich/Switzerland'
__version__ = '2023112901' # adapt this if something in this script changed fundamentally

DESCRIPTION = """Simply creates the file "endoflifedate.py" for a given list of products."""

DEFAULT_FILE = 'lib/endoflifedate.py'

VERSION = '2025022301' # adapt this if one of PRODUCTS was added/deleted
PRODUCTS = [
    'https://endoflife.date/api/apache.json',
    'https://endoflife.date/api/composer.json',
    'https://endoflife.date/api/fedora.json',
    'https://endoflife.date/api/fortios.json',
    'https://endoflife.date/api/gitlab.json',
    'https://endoflife.date/api/grafana.json',
    'https://endoflife.date/api/graylog.json',
    'https://endoflife.date/api/keycloak.json',
    'https://endoflife.date/api/mariadb.json',
    'https://endoflife.date/api/mastodon.json',
    'https://endoflife.date/api/matomo.json',
    'https://endoflife.date/api/mediawiki.json',
    'https://endoflife.date/api/moodle.json',
    'https://endoflife.date/api/mysql.json',
    'https://endoflife.date/api/nextcloud.json',
    'https://endoflife.date/api/openvpn.json',
    'https://endoflife.date/api/php.json',
    'https://endoflife.date/api/postfix.json',
    'https://endoflife.date/api/postgresql.json',
    'https://endoflife.date/api/python.json',
    'https://endoflife.date/api/redhat-build-of-openjdk.json',
    'https://endoflife.date/api/redis.json',
    'https://endoflife.date/api/rhel.json',
    'https://endoflife.date/api/rocketchat.json',
    'https://endoflife.date/api/solr.json',
    'https://endoflife.date/api/wordpress.json',
]


def parse_args():
    """Parse command line arguments using argparse.
    """
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument(
        '-V', '--version',
        action='version',
        version='%(prog)s: v{} by {}'.format(__version__, __author__)
    )

    parser.add_argument(
        '--file',
        help='Path to endoflifedate.py. Default: %(default)s',
        dest='FILE',
        default=DEFAULT_FILE,
    )

    return parser.parse_args()


def main():
    """The main function. Hier spielt die Musik.
    """

    # parse the command line, exit with UNKNOWN if it fails
    try:
        args = parse_args()
    except SystemExit:
        sys.exit(STATE_UNKNOWN)

    endoflifedate_py = '''#! /usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.rst

"""This library stores information from https://endoflife.date/api/ for offline usage
and therefore needs to be updated periodically when version checks don't have access to the
Internet."""

# pylint: disable=C0302

__author__ = 'Linuxfabrik GmbH, Zurich/Switzerland'
__version__ = '2023112901'

ENDOFLIFE_DATE = {

'''.replace('VERSION', VERSION)

    # fetch data
    for product in PRODUCTS:
        j = lib.base.coe(lib.url.fetch_json(product))
        j = pprint.pformat(j, indent=4, sort_dicts=True)
        endoflifedate_py += '    \'{}\': {},\n\n\n'.format(
            product,
            j.replace('[ ', '[\n  ').replace(']', ',\n    ]'),
        )

    endoflifedate_py += '}\n'

    lib.disk.write_file(args.FILE, endoflifedate_py)


if __name__ == '__main__':
    try:
        main()
    except Exception:   # pylint: disable=W0703
        lib.base.cu()
