#!/usr/bin/env python3
# -*- coding: utf-8; py-indent-offset: 4 -*-
#
# Author:  Linuxfabrik GmbH, Zurich, Switzerland
# Contact: info (at) linuxfabrik (dot) ch
#          https://www.linuxfabrik.ch/
# License: The Unlicense, see LICENSE file.

# https://github.com/Linuxfabrik/lib/blob/main/CONTRIBUTING.md

"""Unit tests for lib.endoflifedate (bundled end-of-life data table)."""

import sys
import unittest

sys.path.insert(0, '..')

import lib.endoflifedate as eol


class TestEndOfLifeData(unittest.TestCase):
    def test_table_is_non_empty_dict(self):
        self.assertIsInstance(eol.ENDOFLIFE_DATE, dict)
        self.assertGreater(len(eol.ENDOFLIFE_DATE), 0)

    def test_keys_are_urls_with_list_values(self):
        for key, value in eol.ENDOFLIFE_DATE.items():
            self.assertTrue(key.startswith('http'), key)
            self.assertIsInstance(value, list)


if __name__ == '__main__':
    unittest.main()
