name: 'Linuxfabrik: Auto Versioning on Push'

on:
  push:
    branches:
      - 'main'

jobs:
  versioning:
    uses: 'Linuxfabrik/autoinc-semver/.github/workflows/autoinc-semver.yml@main'
    secrets: 'inherit'
 